In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# Define the input tensor.
batch_size = 2
seq_len = 3
hidden_size = 4
x = torch.randn(batch_size, seq_len, hidden_size)
print("Input tensor shape:", x.shape)
print("Input tensor:\n", x)

# PyTorch's built-in LayerNorm implementation.
layer_norm_pytorch = nn.LayerNorm(hidden_size)
output_pytorch = layer_norm_pytorch(x)
print("\nPyTorch LayerNorm output:\n", output_pytorch)

# Manual implementation of LayerNorm.
def manual_layer_norm(x, eps=1e-5):
    """
    Manual implementation of LayerNorm without using PyTorch's built-in functions.
    
    Args:
        x: Input tensor of shape [batch_size, seq_len, hidden_size].
        eps: Small constant for numerical stability.
    
    Returns:
        Normalized tensor of the same shape as input.
    """
    # Calculate mean along the last dimension.
    mean = x.mean(dim=-1, keepdim=True)
    
    # Calculate variance along the last dimension.
    var = ((x - mean) ** 2).mean(dim=-1, keepdim=True)
    
    # Normalize the input.
    x_norm = (x - mean) / torch.sqrt(var + eps)
    
    # In a complete implementation, we would also have learnable parameters
    # gamma (scale) and beta (shift), but for simplicity, we're omitting them.
    # If needed, they would be applied as: x_norm * gamma + beta
    
    return x_norm

# Apply our manual LayerNorm.
output_manual = manual_layer_norm(x)
print("\nManual LayerNorm output:\n", output_manual)

# Complete manual implementation with learnable parameters.
class ManualLayerNorm(nn.Module):
    """
    Complete manual implementation of LayerNorm with learnable parameters.
    """
    def __init__(self, normalized_shape, eps=1e-5):
        """
        Initialize the LayerNorm module.
        
        Args:
            normalized_shape: Size of the last dimension of input tensor.
            eps: Small constant for numerical stability.
        """
        super(ManualLayerNorm, self).__init__()
        self.eps = eps
        self.gamma = nn.Parameter(torch.ones(normalized_shape))
        self.beta = nn.Parameter(torch.zeros(normalized_shape))
    
    def forward(self, x):
        """
        Forward pass of the LayerNorm module.
        
        Args:
            x: Input tensor of shape [..., normalized_shape].
        
        Returns:
            Normalized tensor of the same shape as input.
        """
        mean = x.mean(dim=-1, keepdim=True)
        var = ((x - mean) ** 2).mean(dim=-1, keepdim=True)
        x_norm = (x - mean) / torch.sqrt(var + self.eps)
        
        # Apply scale and shift.
        return x_norm * self.gamma + self.beta

# Create and apply our complete manual LayerNorm.
manual_ln_module = ManualLayerNorm(hidden_size)
output_manual_module = manual_ln_module(x)
print("\nManual LayerNorm with learnable parameters output:\n", output_manual_module)

# Verify that our implementation matches PyTorch's.
print("\nDifference between PyTorch and our manual implementation:")
print(torch.abs(output_pytorch - output_manual_module).max().item())


Input tensor shape: torch.Size([2, 3, 4])
Input tensor:
 tensor([[[ 0.1803,  0.6033,  1.4754, -1.3303],
         [ 0.2769, -1.9162,  1.5147,  1.0496],
         [ 1.0186, -1.0842,  0.1857,  0.1886]],

        [[ 0.1272, -0.7242, -0.9807,  0.7961],
         [ 0.6597, -1.2855, -0.4190, -0.5322],
         [ 0.4731, -2.6446,  0.5332, -0.6220]]])

PyTorch LayerNorm output:
 tensor([[[-0.0510,  0.3654,  1.2239, -1.5382],
         [ 0.0347, -1.6314,  0.9750,  0.6217],
         [ 1.2527, -1.5453,  0.1444,  0.1483]],

        [[ 0.4581, -0.7509, -1.1152,  1.4080],
         [ 1.5193, -1.2848, -0.0357, -0.1989],
         [ 0.8075, -1.6175,  0.8542, -0.0443]]],
       grad_fn=<NativeLayerNormBackward0>)

Manual LayerNorm output:
 tensor([[[-0.0510,  0.3654,  1.2239, -1.5382],
         [ 0.0347, -1.6314,  0.9750,  0.6217],
         [ 1.2527, -1.5453,  0.1444,  0.1483]],

        [[ 0.4581, -0.7509, -1.1152,  1.4080],
         [ 1.5193, -1.2848, -0.0357, -0.1989],
         [ 0.8075, -1.6175,  0.8542,

In [ ]:
# %% cell 1 code
import torch
import torch.nn as nn
import torch.nn.functional as F

# Define the input tensor.
batch_size = 2
seq_len = 3
hidden_size = 4
x = torch.randn(batch_size, seq_len, hidden_size)
print("Input tensor shape:", x.shape)
print("Input tensor:\n", x)

# PyTorch's built-in LayerNorm implementation.
layer_norm_pytorch = nn.LayerNorm(hidden_size)
output_pytorch = layer_norm_pytorch(x)
print("\nPyTorch LayerNorm output:\n", output_pytorch)

# Manual implementation of LayerNorm.
def manual_layer_norm(x, eps=1e-5):
    """
    Manual implementation of LayerNorm without using PyTorch's built-in functions.
    
    Args:
        x: Input tensor of shape [batch_size, seq_len, hidden_size].
        eps: Small constant for numerical stability.
    
    Returns:
        Normalized tensor of the same shape as input.
    """
    # Calculate mean along the last dimension.
    mean = x.mean(dim=-1, keepdim=True)
    
    # Calculate variance along the last dimension.
    var = ((x - mean) ** 2).mean(dim=-1, keepdim=True)
    
    # Normalize the input.
    x_norm = (x - mean) / torch.sqrt(var + eps)
    
    # In a complete implementation, we would also have learnable parameters
    # gamma (scale) and beta (shift), but for simplicity, we're omitting them.
    # If needed, they would be applied as: x_norm * gamma + beta
    
    return x_norm

# Apply our manual LayerNorm.
output_manual = manual_layer_norm(x)
